spring:
  application:
    name: desafio-vagauol
  threads:
    virtual:
      enabled: true
  datasource:
    password: 3030
    url: jdbc:h2:mem:testedb
    username: gomes
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

logging:
  level:
    dev.valente: debug

server:
  error:
    include-stacktrace: on_param
  servlet:
    context-path: /
  tomcat:
    threads:
      max: 20
